export { default as Dialog } from '@lana-care/ui/components/dialog/Dialog.vue'
export { default as DialogTrigger } from '@lana-care/ui/components/dialog/DialogTrigger.vue'
export { default as DialogContent } from '@lana-care/ui/components/dialog/DialogContent.vue'
export { default as DialogHeader } from '@lana-care/ui/components/dialog/DialogHeader.vue'
export { default as DialogTitle } from '@lana-care/ui/components/dialog/DialogTitle.vue'
export { default as DialogDescription } from '@lana-care/ui/components/dialog/DialogDescription.vue'
export { default as DialogFooter } from '@lana-care/ui/components/dialog/DialogFooter.vue'
export { default as DialogClose } from '@lana-care/ui/components/dialog/DialogClose.vue'
